{% set name = "rbdl-casadi" %}
{% set version = "2.6.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pariterre/rbdl-casadi/archive/fcffaacca2248832d7e9033c852cb6ee13cefafb.zip
  sha256: ddee7591a2525fd34ab4efd63ed7b7cea30482a3a4e3158e24ef99f39fde6d4d
build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - casadi
  run:
    - casadi

test:
  commands:
    - test $PREFIX/lib/librbdl$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\rbdl*.lib exit 1  # [win]

about:
  home: https://bitbucket.org/rbdl/rbdl
  license: Zlib
  license_file: LICENSE
  license_family: OTHER
  summary: RBDL is a highly efficient C++ library that contains some essential rigid body dynamics algorithms with CasADi backend

extra:
  recipe-maintainers:
    - pariterre
